#ifndef AKARI_GRAPHCIS_VULKAN_CORE_AKARI_VK_CORE_DEVICE_H
#define AKARI_GRAPHCIS_VULKAN_CORE_AKARI_VK_CORE_DEVICE_H
#include <Akari/Graphics/Vulkan/Core/AkariVKCore.h>
#include <string_view>
#include <tuple>
AKARI_GRAPHICS_VULKAN_CORE_NAMESPACE_BEGIN
namespace Test {

}

AKARI_GRAPHICS_VULKAN_CORE_NAMESPACE_END
#endif