#ifndef AKARI_GRAPHICS_VK_CORE_SWAP_CHAIN_H
#define AKARI_GRAPHICS_VK_CORE_SWAP_CHAIN_H
#include <Akari/Graphics/Vulkan/Core/AkariVKCore.h>
AKARI_GRAPHICS_VULKAN_CORE_NAMESPACE_BEGIN

class AkariVKSwapchain
{

};

AKARI_GRAPHICS_VULKAN_CORE_NAMESPACE_END
#endif